### ISSUE TITLE
Strong naming discrepancy

### ISSUE THREAD

**Issue by mrtaunus** [zzzprojects/Dapper.Transaction#2]
The Dapper.Transaction package is marked as strong named, but instead of having a dependency on Dapper.StrongName, it has a dependency on Dapper. 

Preferably both version should be available of the Dapper transaction package, but for majority of use cases, non-strong named version would be more suitable. In any case, the strong naming should be in line with the dependencies.

**Comment by JonathanMagnan** [comment]
Thank you for reporting @mrtaunus,

We will look at what we should do here and make the required change at the beginning of next week probably.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @mrtaunus ,

Thank again for reporting, still feel weird that after 7k downloads you are the first one reporting that the NuGet package never worked at all ;)

Anyway,

2 NuGet is now available (and have been correctly tested this time!):
- https://www.nuget.org/packages/Dapper.Transaction/
- https://www.nuget.org/packages/Dapper.Transaction.StrongName/

If there is anything else, let us know.

Best Regards,

Jon

**Comment by mrtaunus** [comment]
Hi @JonathanMagnan,

Indeed peculiar, that no-one else has reported this =)

Thanks for quick action. The non-strong named version now works correctly. Did not test the strong named one, but based on a quick code review that should be fine, too.

Best regards,
Tuukka
