### ISSUE TITLE
MySQL: The transaction associated with this command is not the connection’s active transaction

### ISSUE THREAD

**Issue by shoe-diamente** [zzzprojects/Dapper.Transaction#3]
Whenever I use this library with MySQL I get [this error](https://mysqlconnector.net/troubleshooting/transaction-usage/):

> System.InvalidOperationException: The transaction associated with this command is not the connection’s active transaction; see https://fl.vu/mysql-trans

The example code is:

```c-sharp
using var transaction = connection.BeginTransaction();
var someBool = await transaction.QuerySingleAsync<bool>(
                new CommandDefinition("SELECT true;", cancellationToken: ct));
```

I'm using these libraries with .NET Core 3.1:

```xml
<PackageReference Include="Dapper" Version="2.0.35" />
<PackageReference Include="Dapper.Transaction" Version="2.0.35.2" />
<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="3.1.1" />
```

That error should happen when there's a query not using the transaction within a transaction "scope".
How is it possible with this library? Am I doing something wrong?

**Comment by JonathanMagnan** [comment]
Thank you for reporting, we will look at it.

It seems that the connection we retrieve from the transaction might be the wrong one for Pomelo.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @shoe-diamente ,

My developer tried it but everything is working on his side.

However, he found this troubleshooting: https://mysqlconnector.net/troubleshooting/transaction-usage/

Which speaks a lot of `Dapper` and why and how to fix this error.

Perhaps, that's the error on your side?

**Comment by shoe-diamente** [comment]
That must be it. I can't try it at the moment but we can close this issue for now.
When I'll get around to it if the problem persists I'll come back here with a reproducible example.
Thanks for the quick response.
