### ISSUE TITLE
Transactions Rollback for MySQL (Innodb) (AWS Aurora) is not working

### ISSUE THREAD

**Issue by angelalaweai** [zzzprojects/Dapper.Transaction#4]
.Net Core 3.1

this is a shortened version to give you how I am doing it.  But I have tried ever which way through dapper and through dappertransactions to get it to roll back but I can't.  I know it will rollback through the normal ado.net with mysqlcommand because I tried it.

Doesn't Worl  --- some code that didn't matter was taken out so it is not as long...So this is the basic gist.  The district and school information never get rolled back even through the dbTrans.Rollback(); is being hit and no error is occuring when it is called.

using Dapper.Transaction;

            using (_dbConnection)
            {
                _dbConnection.Open();
                using (var dbTrans = _dbConnection.BeginTransaction())
                {
                    try
                    {
                        DynamicParameters dpDistrict = new DynamicParameters(parms);
                        dpDistrict.Add("p_DistrictId", DbType.Int32, 0, ParameterDirection.Output);

                        //Save the district so we have the new id for the inserting the school
                        dbTrans.Execute("District_Ins", dpDistrict, commandType: CommandType.StoredProcedure);
                        var districtId = dpDistrict.Get<dynamic>("p_districtId");

                        districtInfo.DistrictId = districtId;

                        if (districtInfo.Schools != null)
                            for (var i = 0; i < districtInfo.Schools.Count; i++)
                            {
                                DynamicParameters dpSchool = new DynamicParameters(schoolParms);
                                dpDistrict.Add("p_SchoolId", DbType.Int32, 0, ParameterDirection.Output);

                                //Save the school so we have the new id for the inserted school
                                dbTrans.Execute("School_Ins", dpSchool, commandType: CommandType.StoredProcedure);
                                var schoolId = dpDistrict.Get<dynamic>("p_SchoolId");
                                
                                throw new Exception("");

                                foreach (var newGrade in school.Grades)
                                {
                                    dbTrans.Execute("XSchoolGrade_Ins", gradeInsParms, commandType: CommandType.StoredProcedure);
                                }
                            }
                        dbTrans.Commit();
                        return newDistrictInfo;
                    }
                    catch (Exception exception)
                    {
                        dbTrans.Rollback();
                        _logger.Error(exception, districtInfo);
                        throw;
                    }
                }

**Comment by JonathanMagnan** [comment]
Hello @angelalaweai ,

Do it works directly with the connection using Dapper extensions and you pass the transaction as a parameter?

Our library pretty much just directly use Dapper, so I'm not sure why it would fail with our library and not directly with dapper.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
