### ISSUE TITLE
No full support for Dapper Methods...

### ISSUE THREAD

**Issue by MBurchard** [zzzprojects/Dapper.Transaction#5]
> Everything Dapper support, Dapper Transaction support it as well (It's only new extension method calling Dapper)

Dapper supports `ExecuteScalarAsync<T>()`, while Dapper Transaction not

**Comment by JonathanMagnan** [comment]
Hello @MBurchard ,

Are you sure?

Look for me that's already supported: https://github.com/zzzprojects/Dapper.Transaction/blob/master/Dapper.Transaction.Shared/DbTransaction/Extensions/ExecuteScalarAsync%60.cs#L18

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by MBurchard** [comment]
Sorry, you are right... may be it's already much too late in Germany... Sorry...
